<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '';
echo '<head>';
echo '';
echo '<meta charset="utf-8">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">';
echo '<meta name="description" content="">';
echo '<meta name="author" content="">';
echo '<link href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&display=swap" rel="stylesheet">';
echo '';
echo '<title>ADZE Fitness Studio</title>';
echo '';
echo '<!--';
echo '';
echo 'TemplateMo 548 Training Studio';
echo '';
echo 'https://templatemo.com/tm-548-training-studio';
echo '';
echo '-->';
echo '';
echo '<!-- Additional CSS Files -->';
echo '<link rel="stylesheet" type="text/css" href="assets/css/bootstrap.min.css">';
echo '';
echo '<link rel="stylesheet" type="text/css" href="assets/css/font-awesome.css">';
echo '';
echo '<link rel="stylesheet" href="assets/css/templatemo-training-studio.css">';
echo '';
echo '</head>';
echo '';
echo '<body>';
echo '';
echo '<!-- ***** Preloader Start ***** -->';
echo '<div id="js-preloader" class="js-preloader">';
echo '<div class="preloader-inner">';
echo '<span class="dot"></span>';
echo '<div class="dots">';
echo '<span></span>';
echo '<span></span>';
echo '<span></span>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!-- ***** Preloader End ***** -->';
echo '';
echo '';
echo '<!-- ***** Header Area Start ***** -->';
echo '<header class="header-area header-sticky">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-12">';
echo '<nav class="main-nav">';
echo '<!-- ***** Logo Start ***** -->';
echo '<a href="index.html" class="logo"><em> ADZE </em>Fitness Studio</a>';
echo '<!-- ***** Logo End ***** -->';
echo '<!-- ***** Menu Start ***** -->';
echo '<ul class="nav">';
echo '<li class="scroll-to-section"><a href="#top" class="active">Home</a></li>';
echo '<li class="scroll-to-section"><a href="#features">About</a></li>';
echo '<li class="scroll-to-section"><a href="#our-classes">Classes</a></li>';
echo '<li class="scroll-to-section"><a href="#trainers">Trainers</a></li>';
echo '<li class="scroll-to-section"><a href="#review">Review</a></li>';
echo '<li class="scroll-to-section"><a href="#contact-us">Contact</a></li>';
echo '<li class="scroll-to-section"><a href="#contact-us">Sign Up</a></li>';
echo '</ul>';
echo '<a class='menu-trigger'>';
echo '<span>Menu</span>';
echo '</a>';
echo '<!-- ***** Menu End ***** -->';
echo '</nav>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</header>';
echo '<!-- ***** Header Area End ***** -->';
echo '';
echo '<!-- ***** Main Banner Area Start ***** -->';
echo '<div class="main-banner" id="top">';
echo '<video autoplay muted loop id="bg-video">';
echo '<source src="assets/images/gym-video.mp4" type="video/mp4" />';
echo '</video>';
echo '';
echo '<div class="video-overlay header-text">';
echo '<div class="caption">';
echo '<h6>work harder, get stronger</h6>';
echo '<br>';
echo '<h2>easy with our <em>gym</em></h2>';
echo '<div class="main-button scroll-to-section">';
echo '<a href="#features">Become a member</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!-- ***** Main Banner Area End ***** -->';
echo '';
echo '<!-- ***** Features Item Start ***** -->';
echo '<section class="section" id="features">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-lg-6 offset-lg-3">';
echo '<div class="section-heading">';
echo '<h2>Choose <em>Program</em></h2>';
echo '<img src="assets/images/line-dec.png" alt="waves">';
echo '<p>The clock is ticking. Are you becoming the person you want to be?</p>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-6" style="padding-left: 130px;">';
echo '<ul class="features-items">';
echo '<li class="feature-item">';
echo '<div class="left-icon">';
echo '<img src="assets/images/features-first-icon.png" alt="First One" style="height: 120px;">';
echo '</div>';
echo '<div class="right-content">';
echo '<h4>Internationally Certified Training</h4>';
echo '<p style="width: 900px;">Please do not re-distribute this template ZIP file on any template collection website. This is not allowed.</p>';
echo '<a href="#" class="text-button">Discover More</a>';
echo '</div>';
echo '</li>';
echo '<li class="feature-item">';
echo '<div class="left-icon">';
echo '<img src="assets/images/features-first-icon.png" alt="second one" style="height: 120px;">';
echo '</div>';
echo '<div class="right-content">';
echo '<h4>30 Days - Rapid Fat Loss Programm</h4>';
echo '<p style="width: 900px;">If you wish to support TemplateMo website via PayPal, please feel free to contact us. We appreciate it a lot.</p>';
echo '<a href="#" class="text-button">Discover More</a>';
echo '</div>';
echo '</li>';
echo '<li class="feature-item">';
echo '<div class="left-icon">';
echo '<img src="assets/images/features-first-icon.png" alt="third gym training" style="height: 120px;">';
echo '</div>';
echo '<div class="right-content">';
echo '<h4>Online & At Home Coaching</h4>';
echo '<p style="width: 900px;">Going to the gym isn’t the only way to get in a great workout. Working out at home can be just as effective. While a gym provides a dedicated space, home workouts offer more flexibility and can be more efficient.</p>';
echo '<a href="#" class="text-button">Discover More</a>';
echo '';
echo '</div>';
echo '</li>';
echo '';
echo '<li class="feature-item">';
echo '<div class="left-icon">';
echo '<img src="assets/images/features-first-icon.png" alt="fourth muscle" style="height: 120px;">';
echo '</div>';
echo '<div class="right-content">';
echo '<h4>Corrective Exercise - (Physio)</h4>';
echo '<p style="width: 950px;">Corrective Exercise is a technique that leverages an understanding of anatomy, kinesiology, and biomechanics to address and fix movement compensations and imbalances to improve the overall quality of movement during workouts and in everyday life.Corrective Exercise is used to help assess and determine the root cause of imbalances and faulty movement patterns that lead to issues with posture, balance, and total body coordination.</p>';
echo '</div>';
echo '</li>';
echo '<li class="feature-item">';
echo '<div class="left-icon">';
echo '<img src="assets/images/features-first-icon.png" alt="training fifth" style="height: 120px;">';
echo '</div>';
echo '<div class="right-content">';
echo '<h4>HIIT with Mindset Development </h4>';
echo '<p style="width: 900px;">HIIT involves short bursts of intense exercise alternated with low-intensity recovery periods. Interestingly, it is perhaps the most time-efficient way to exercise.Typically, a HIIT workout will range from 10 to 30 minutes in duration.Despite how short the workout is, it can produce health benefits similar to twice as much moderate-intensity exercise.</p>';
echo '';
echo '</div>';
echo '</li>';
echo '<li class="feature-item">';
echo '<div class="left-icon">';
echo '<img src="assets/images/features-first-icon.png" alt="gym training" style="height: 120px;">';
echo '</div>';
echo '<div class="right-content">';
echo '<h4>Nutrition & Diet Plan</h4>';
echo '<p style="width: 900px;">The importance of a balanced diet can’t be emphasized enough for a healthy lifestyle. A healthy lifestyle can be attained by maintaining a balanced diet and keeping into consideration to meet all the essential nutrients required by the body. </p>';
echo '</div>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '';
echo '</div>';
echo '</div>';
echo '</section>';
echo '<!-- ***** Features Item End ***** -->';
echo '';
echo '<!-- ***** Call to Action Start ***** -->';
echo '<section class="section" id="call-to-action">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-lg-10 offset-lg-1">';
echo '<div class="cta-content">';
echo '<h2>Don’t <em>think</em>, begin <em>today</em>!</h2>';
echo '<p>If you want something you’ve never had, you must be willing to do something you’ve never done.</p>';
echo '<div class="main-button scroll-to-section">';
echo '<a href="#our-classes">Become a member</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '<!-- ***** Call to Action End ***** -->';
echo '';
echo '<!-- ***** Our Classes Start ***** -->';
echo '<section class="section" id="our-classes">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-lg-6 offset-lg-3">';
echo '<div class="section-heading">';
echo '<h2>Our <em>Classes</em></h2>';
echo '<img src="assets/images/line-dec.png" alt="">';
echo '<p>Success is walking from failure to failure with no loss of enthusiasm.</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="row" id="tabs">';
echo '<div class="col-lg-4" style="padding-top: 20px;">';
echo '<ul>';
echo '<li><a href='#tabs-1'><img src="assets/images/tabs-first-icon.png" alt="">Stretches & Warm-Up</a></li>';
echo '<li><a href='#tabs-2'><img src="assets/images/tabs-first-icon.png" alt="">Corrective Exercises</a></a></li>';
echo '<li><a href='#tabs-3'><img src="assets/images/tabs-first-icon.png" alt="">Functional Training</a></a></li>';
echo '<li><a href='#tabs-4'><img src="assets/images/tabs-first-icon.png" alt="">Resistance Training</a></a></li>';
echo '</ul>';
echo '</div>';
echo '<div class="col-lg-8">';
echo '<section class='tabs-content'>';
echo '<article id='tabs-1'>';
echo '<img src="assets/images/training-image-04.jpg" alt="First Class">';
echo '<h4>Stretches & Warm-Up</h4>';
echo '<p>Warming up before a workout is an important step toward injury prevention. A proper warm up increases flexibility and blood flow to a given area, which limits the chance of a muscle pull and joint pain. Warming up also prepares your muscles to stretch during other exercises.</p>';
echo '';
echo '</article>';
echo '<article id='tabs-2'>';
echo '<img src="assets/images/training-image-03.jpg" alt="Second Training">';
echo '<h4>Corrective Exercises</h4>';
echo '<p>Corrective Exercise is a technique that leverages an understanding of anatomy, kinesiology, and biomechanics to address and fix movement compensations and imbalances to improve the overall quality of movement during workouts and in everyday life.Corrective Exercise is used to help assess and determine the root cause of imbalances and faulty movement patterns that lead to issues with posture, balance, and total body coordination.</p>';
echo '';
echo '</article>';
echo '<article id='tabs-3'>';
echo '<img src="assets/images/training-image-01.jpg" alt="Third Class">';
echo '<h4>Functional Training</h4>';
echo '<p>Functional training is a term used to describe exercises that help you perform activities in everyday life more easily. These exercises typically use the whole body — definitely multiple muscles — and emphasize core strength and stability. By mirroring the movements of your daily life, like squatting, reaching, or even carrying a heavy object, building functional strength can help increase your quality of life and reduce your risk of injury.</p>';
echo '';
echo '</article>';
echo '<article id='tabs-4'>';
echo '<img src="assets/images/training-image-02.jpg" alt="Fourth Training">';
echo '<h4>Resistance Training</h4>';
echo '<p>Resistance training is more commonly referred to by gym goers as weight training but the term refers to any form of exercise where you lift or pull against resistance. This could be using dumbells, a barbell, bodyweight, machines, kettlebells, powerbands or any other external resistance.</p>';
echo '';
echo '</article>';
echo '</section>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '<!-- ***** Our Classes End ***** -->';
echo '';
echo '<!--';
echo '<section class="section" id="schedule">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-lg-6 offset-lg-3">';
echo '<div class="section-heading dark-bg">';
echo '<h2>Classes <em>Schedule</em></h2>';
echo '<img src="assets/images/line-dec.png" alt="">';
echo '<p>Nunc urna sem, laoreet ut metus id, aliquet consequat magna. Sed viverra ipsum dolor, ultricies fermentum massa consequat eu.</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="row">';
echo '<div class="col-lg-12">';
echo '<div class="filters">';
echo '<ul class="schedule-filter">';
echo '<li class="active" data-tsfilter="monday">Monday</li>';
echo '<li data-tsfilter="tuesday">Tuesday</li>';
echo '<li data-tsfilter="wednesday">Wednesday</li>';
echo '<li data-tsfilter="thursday">Thursday</li>';
echo '<li data-tsfilter="friday">Friday</li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-10 offset-lg-1">';
echo '<div class="schedule-table filtering">';
echo '<table>';
echo '<tbody>';
echo '<tr>';
echo '<td class="day-time">Fitness Class</td>';
echo '<td class="monday ts-item show" data-tsmeta="monday">10:00AM - 11:30AM</td>';
echo '<td class="tuesday ts-item" data-tsmeta="tuesday">2:00PM - 3:30PM</td>';
echo '<td>William G. Stewart</td>';
echo '</tr>';
echo '<tr>';
echo '<td class="day-time">Muscle Training</td>';
echo '<td class="friday ts-item" data-tsmeta="friday">10:00AM - 11:30AM</td>';
echo '<td class="thursday friday ts-item" data-tsmeta="thursday" data-tsmeta="friday">2:00PM - 3:30PM</td>';
echo '<td>Paul D. Newman</td>';
echo '</tr>';
echo '<tr>';
echo '<td class="day-time">Body Building</td>';
echo '<td class="tuesday ts-item" data-tsmeta="tuesday">10:00AM - 11:30AM</td>';
echo '<td class="monday ts-item show" data-tsmeta="monday">2:00PM - 3:30PM</td>';
echo '<td>Boyd C. Harris</td>';
echo '</tr>';
echo '<tr>';
echo '<td class="day-time">Yoga Training Class</td>';
echo '<td class="wednesday ts-item" data-tsmeta="wednesday">10:00AM - 11:30AM</td>';
echo '<td class="friday ts-item" data-tsmeta="friday">2:00PM - 3:30PM</td>';
echo '<td>Hector T. Daigle</td>';
echo '</tr>';
echo '<tr>';
echo '<td class="day-time">Advanced Training</td>';
echo '<td class="thursday ts-item" data-tsmeta="thursday">10:00AM - 11:30AM</td>';
echo '<td class="wednesday ts-item" data-tsmeta="wednesday">2:00PM - 3:30PM</td>';
echo '<td>Bret D. Bowers</td>';
echo '</tr>';
echo '</tbody>';
echo '</table>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '-->';
echo '';
echo '<!-- ***** Testimonials Starts ***** -->';
echo '<section class="section" id="trainers">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-lg-6 offset-lg-3">';
echo '<div class="section-heading">';
echo '<h2>Expert <em>Trainers</em></h2>';
echo '<img src="assets/images/line-dec.png" alt="">';
echo '<p>Don’t stop when you’re tired. Stop when you’re done</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="row">';
echo '<div class="col-lg-4">';
echo '<div class="trainer-item">';
echo '<div class="image-thumb">';
echo '<img src="assets/images/first-trainer.jpg" alt="">';
echo '</div>';
echo '<div class="down-content">';
echo '<span>Strength Trainer</span>';
echo '<h4>V Samuel Jackson</h4>';
echo '<p> Bcom C.S. Started from 2017, new skill academy certification on fitness, persuading diploma from sports massage, advanced nutrition,  ACE certification and any certification to broaded my knowledge.';
echo 'can train from teen to geriatric, specified chronic patients, sports specific, post and pre rehab, posture correction.</p>';
echo '<ul class="social-icons">';
echo '<li><a href="#"><i class="fa fa-instagram"></i></a></li>';
echo '<li><a href="#"><i class="fa fa-linkedin"></i></a></li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-4">';
echo '<div class="trainer-item">';
echo '<div class="image-thumb">';
echo '<img src="assets/images/second-trainer.jpeg" alt="">';
echo '</div>';
echo '<div class="down-content">';
echo '<span>Muscle Trainer</span>';
echo '<h4>Anantha krishnan R</h4>';
echo '<p> M.com. 3 years experience in ground fitness and athletics. Agility and endurance training,flexlibility,muscular strength and HIIT</p>';
echo '<ul class="social-icons">';
echo '<li><a href="#"><i class="fa fa-instagram"></i></a></li>';
echo '<li><a href="#"><i class="fa fa-linkedin"></i></a></li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-4">';
echo '<div class="trainer-item">';
echo '<div class="image-thumb">';
echo '<img src="assets/images/third-trainer.jpeg" alt="">';
echo '</div>';
echo '<div class="down-content">';
echo '<span>Power Trainer</span>';
echo '<h4>Sabarinathan</h4>';
echo '<p>CFR PRO ,(studying- NASM CPT & MSC  in FERNC), 2 Years experience, Specialisation in corrective workouts poster alignment and can treat basic problems like flat foot, pelvic tilt, rounded Shoulders, stiff back, back pain scoliosis etc..., Hypertrophy weight gaining and muscle building</p>';
echo '<ul class="social-icons">';
echo '<li><a href="#"><i class="fa fa-instagram"></i></a></li>';
echo '<li><a href="#"><i class="fa fa-linkedin"></i></a></li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '<!-- ***** Testimonials Ends ***** -->';
echo '';
echo '';
echo '<section class="section" id="review">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-lg-6 offset-lg-3">';
echo '<div class="section-heading">';
echo '<h2>Power Packed <em>Testimonials</em></h2>';
echo '<img src="assets/images/line-dec.png" alt="">';
echo '<p>Don’t stop when you’re tired. Stop when you’re done</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="row">';
echo '<div class="col-lg-4">';
echo '<div class="trainer-item">';
echo '<div class="image-thumb">';
echo '<img src="assets/images/first-review.png" alt="">';
echo '</div>';
echo '<div class="down-content">';
echo '<a href="https://goo.gl/maps/xKhBAZEqn5uwCVSA6" target="_blank"><span > Google Review Link</span></a>';
echo '<h4>Ram M</h4>';
echo '<p> Got a fantastic trainer Mr.Sabari (International Certified) in Adze Fitness.I felt the workout he guided,the way he explain about every workout is fabulous one,keep doing bro,all the best for your career in FITNESS  💪</p>';
echo '';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-4">';
echo '<div class="trainer-item">';
echo '<div class="image-thumb">';
echo '<img src="assets/images/second-review.png" alt="">';
echo '</div>';
echo '<div class="down-content">';
echo '<a href="https://g.co/kgs/z3dpDg" target="_blank"><span > Google Review Link</span></a>';
echo '<h4>Harish ady</h4>';
echo '<p> ADZE Fitness Studio one the best fitness Studio I ever seen till now. It's specialty is trainers are polite and friendly then my trainer Mr.Sabari (International certified) is my best trainer in there. I would also suggest u guys this fitness studio because it's perfect for all.</p>';
echo '';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-4">';
echo '<div class="trainer-item">';
echo '<div class="image-thumb">';
echo '<img src="assets/images/third-review.png" alt="">';
echo '</div>';
echo '<div class="down-content">';
echo '<a href="https://goo.gl/maps/Ut4uGz4KoNmwHF2Z6" target="_blank"><span > Google Review Link</span></a>';
echo '<h4>Manoj Logu</h4>';
echo '<p>Mr.Sabari is an excellent international fitness trainer....his knowledge is Amazing in this fitness field....</p>';
echo '';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '';
echo '';
echo '<!-- ***** Contact Us Area Starts ***** -->';
echo '<section class="section" id="contact-us">';
echo '<div class="container-fluid">';
echo '<div class="row">';
echo '<div class="col-lg-6 col-md-6 col-xs-12">';
echo '<div id="map">';
echo '';
echo '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3888.108974503008!2d80.19763651478542!3d12.964878090860292!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3a525dc2a2d4a7f9%3A0x40a2852fde0ec6fc!2sADZE%20Fitness%20Studio%20(Unisex)!5e0!3m2!1sen!2sin!4v1634830874067!5m2!1sen!2sin" width="100%" height="600px" frameborder="0" style="border:0" allowfullscreen></iframe>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-6 col-md-6 col-xs-12">';
echo '<div class="contact-form">';
echo '<form id="contact" action="https://formsubmit.co/vinodv9189@gmail.com" method="post">';
echo '<div class="row">';
echo '<div class="col-md-6 col-sm-12">';
echo '<fieldset>';
echo '<input name="name" type="text" id="name" placeholder="Your Name*" required="">';
echo '</fieldset>';
echo '</div>';
echo '<div class="col-md-6 col-sm-12">';
echo '<fieldset>';
echo '<input name="email" type="text" id="email" pattern="[^ @]*@[^ @]*" placeholder="Your Email*" required="">';
echo '</fieldset>';
echo '</div>';
echo '<div class="col-md-12 col-sm-12">';
echo '<fieldset>';
echo '<input name="subject" type="hidden" id="subject" value="New Message from Client">';
echo '</fieldset>';
echo '</div>';
echo '<div class="col-lg-12">';
echo '<fieldset>';
echo '<textarea name="message" rows="6" id="message" placeholder="Message" required=""></textarea>';
echo '</fieldset>';
echo '</div>';
echo '<div class="col-lg-12">';
echo '<fieldset>';
echo '<button type="submit" id="form-submit" class="main-button">Send Message</button>';
echo '</fieldset>';
echo '</div>';
echo '</div>';
echo '</form>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '<!-- ***** Contact Us Area Ends ***** -->';
echo '';
echo '<!-- ***** Footer Start ***** -->';
echo '<footer>';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-lg-12">';
echo '<p>Copyright &copy; 2020 Training Studio';
echo '';
echo '- Designed by <a rel="nofollow" href="https://templatemo.com" class="tm-text-link" target="_parent">TemplateMo</a></p>';
echo '';
echo '<!-- You shall support us a little via PayPal to info@templatemo.com -->';
echo '';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</footer>';
echo '';
echo '<!-- jQuery -->';
echo '<script src="assets/js/jquery-2.1.0.min.js"></script>';
echo '';
echo '<!-- Bootstrap -->';
echo '<script src="assets/js/popper.js"></script>';
echo '<script src="assets/js/bootstrap.min.js"></script>';
echo '';
echo '<!-- Plugins -->';
echo '<script src="assets/js/scrollreveal.min.js"></script>';
echo '<script src="assets/js/waypoints.min.js"></script>';
echo '<script src="assets/js/jquery.counterup.min.js"></script>';
echo '<script src="assets/js/imgfix.min.js"></script>';
echo '<script src="assets/js/mixitup.js"></script>';
echo '<script src="assets/js/accordions.js"></script>';
echo '';
echo '<!-- Global Init -->';
echo '<script src="assets/js/custom.js"></script>';
echo '';
echo '</body>';
echo '</html>';
?>